### ISSUE TITLE
Better error message when no command given

### ISSUE THREAD

**Issue by jthreefoot-edb** [EnterpriseDB/pg-backup-api#26]
If you enter the command `pg-backup-api` without one of the subcommands (`serve`, `status`), you get the following error

`Traceback (most recent call last):
  File "/usr/bin/pg-backup-api", line 33, in <module>
    sys.exit(load_entry_point('pg-backup-api==0.1.0', 'console_scripts', 'pg-backup-api')())
  File "/usr/lib/python3/dist-packages/pg_backup_api-0.1.0-py3.9.egg/pg_backup_api/run.py", line 103, in main
    return args.func(args)
AttributeError: 'Namespace' object has no attribute 'func'`

which does not explain what the user did wrong or needs to do.

Add a check or something in the CLI handler to intercept this condition/error and present the user with useful help text instead.

**Comment by gonzalemario** [comment]
Sorry for this delay. I couldn't reproduce this bug today. Can you please confirm if it's still present, and in what version/release?
