### ISSUE TITLE
Docs for configuring httpd do not work with selinux

### ISSUE THREAD

**Issue by mikewallace1979** [EnterpriseDB/pg-backup-api#31]
The documentation at https://www.enterprisedb.com/docs/supported-open-source/barman/pg-backup-api/02-securing-pg-backup-api/ puts certificates and keys in /usr/lib/pgbapi.

This works fine except when selinux enabled at which point the httpd process is not allowed to access /usr/lib/pgbapi and therefore cannot start.

The solution is to use `restorecon` to reset the SELinux context for the newly created files.

There is a second problem which is SELinux does not allow httpd to proxy - we have to enable it using `setseboolean`.

**Comment by mikewallace1979** [comment]
This PR should fix things: https://github.com/EnterpriseDB/docs/pull/2614

Tested and verified the RHEL 8 changes with Rocky 8.

Also tested the changes which affect Ubuntu and SLES.

**Comment by jthreefoot-edb** [comment]
With the docs PR merged, can this be closed?
