### ISSUE TITLE
Memory usage increases monotonically

### ISSUE THREAD

**Issue by mikewallace1979** [EnterpriseDB/pg-backup-api#52]
If pg-backup-api is left running its memory usage increases monotonically over time until eventually it is using all available RAM.

This is because the output writer in Barman always [appends new output](https://github.com/EnterpriseDB/barman/blob/19abf787407170c774937457141875af6b6b3a77/barman/output.py#L1124) by design. For Barman this usage was never a problem because a single barman command would be short lived, however using the output writer in pg-backup-api means the json_output object will grow indefinitely.

The proposed solution is to manually clear the json_output object after retrieving the diagnose output: https://github.com/EnterpriseDB/pg-backup-api/pull/50/commits/afbb72d644313f65b38a2a55762c5289c64fbfae

**Comment by bshahakash** [comment]
Do we have any tentative date as of when this request would be worked upon

**Comment by mikewallace1979** [comment]
@bshahakash We'll get a new version out with the fix for this once Barman 3.1.0 is wrapped up

**Comment by mikewallace1979** [comment]
Closed in #50
