### ISSUE TITLE
remove pgespresso from diagnose output

### ISSUE THREAD

**Issue by didiermichel** [EnterpriseDB/pg-backup-api#53]
Barman will drop pgespresso in a future release (https://github.com/EnterpriseDB/barman/issues/601).
This will have an effect on `diagnose output`. The following filed will no longer exits in the output.
`servers.{server_name}.status.pgespresso_installed`
So the idea is to remove it first from this project and later from barman.

**Comment by mikewallace1979** [comment]
Closed in #54
