### ISSUE TITLE
Support for Backup ID shortcuts when Barman is used

### ISSUE THREAD

**Issue by gonzalemario** [EnterpriseDB/pg-backup-api#70]
Barman have "backup shortcuts" to define backup_id instead of using a specific hash, like "latest", "oldest" and so on.

Currently, it seems the api returns with a 404 despite there are backups available.

**Comment by barthisrael** [comment]
I just hit this very same issue while using `pg-backup-api`. I wonder if we can add some logic like [parse_backup_id](https://github.com/EnterpriseDB/barman/blob/master/barman/cli.py#L2035-L2065) from Barman?

**Comment by gonzalemario** [comment]
Feature included now in v1.3.0
